atlantis-url: "https://aa5fe5c88359.ngrok.io"
gh-webhook-secret: "voyage_swim_sense_definition"
gh-token: "e89bb3a9bceb8f6c11d2a7557c4ed4be5dd9874e"
gh-user: "pmamueng"
repo-allowlist: "github.com/pmamueng/Atlantis-Test"